name: py
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: |
            python -m pip install --upgrade pip requests
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute Python script # Run the run.py to get the latest data
        run: python ./bot/main.py
        env:
            CUSTOM_ENV: ${{ secrets.CUSTOM_ENV }}
